export const DASHBOARD = '/habit-tracker'
export const LOG_IN = '/habit-tracker/login'
export const SIGN_UP = '/habit-tracker/signup'
export const MARKETPLACE = '/habit-tracker/marketplace'
export const RESET_PASSWORD = '/habit-tracker/reset-password'
export const PROFILE = '/habit-tracker/profile'
export const SETTINGS = '/habit-tracker/settings'