export const DASHBOARD = '/'
export const LOG_IN = '/login'
export const SIGN_UP = '/signup'
export const MARKETPLACE = '/marketplace'
export const RESET_PASSWORD = '/reset-password'
export const PROFILE = '/profile'
export const SETTINGS = '/settings'